[libdefaults]
    default_realm = HOPSWORKS.AI
    dns_lookup_realm = false
    dns_lookup_kdc = false

[realms]
    HOPSWORKS.AI = {
        kdc = kerberos-kdc.iam.svc.cluster.local
        admin_server = kerberos-kdc.iam.svc.cluster.local
    }

[domain_realm]
    .hopsworks.svc.cluster.local = HOPSWORKS.AI
    hopsworks.svc.cluster.local = HOPSWORKS.AI
